### ISSUE TITLE
Leading zero in value or formula

### ISSUE THREAD

**Issue by ccomb** [brightway-lca/brightway2-parameters#8]
I got `01/03/2005` as a real incoming data for a value or formula:
```
Export AGB 3.1.1 pour tests affichage_10 02 2023.CSV:Orchard, rooting up trees {GLO} - Adapted from WFLDB U;ha;01/03/2005;Undefined;0;0;0;(2,1,1,1,1,na) - According to Neocleous 2008, 10000 plants/ha for open fields. 3 years lifespan.  The amount of biomass is lower than in a typical fruit tree orchard. The amount of material to be extracted and burned is therefore lower. The amount is divided by 5 (pure assumption) to take this into account. 
```
Apart from the fact that it looks like a lost date that found the wrong place, the issue is that it is not accepted by Python:

```
>>> ast.parse("01/03/2005")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    01/03/2005
     ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
>>> asteval.Interpreter()("01/03/2005")
SyntaxError
   01/03/2005
Syntax Error
```

Not sure this should be fixed in bw2parameters with a replacement in the AST, or in bw2io as a strategy (but anyway the strategy needs to parse the formula so this is the job of `ast`.

**Comment by BenPortner** [comment]
Hi @ccomb,

Thanks for using bw2parameters and thanks for the problem analysis. This is a difficult one. Even if the leading zeros are somehow escaped, the string "1/3/2005" would simply be interpreted as a double division (3/5/2005 = 0.0002992518703241895). The only way I see to make it work is to enclose the value in single quotes: `Interpreter()("'01/03/2005' ")`. Where exactly does this value occur? Perhaps we can have a strategy for this particular database with this particular value. Having a general strategy that works for this value and all others will be difficult I'm afraid.

Ben

**Comment by ccomb** [comment]
Thanks for your answer. If we enclose in quotes it ends up as a string. Actually I don't really know if it should really be the division (which corresponds to ~ 1,6m2, or the 01/03/2005 date...  I'll investigate the data source to check.
This problem is as difficult as the formula with `yield` inside. One solution would be to use a different parser.

**Comment by cmutel** [comment]
Leading zeros shouldn't be coming in via user-defined values - we trust our users enough to get the basics right. But they can come in via data imports, and in particular via SimaPro. Therefore I am moving this issue to the SimaPro importer.
